files {
    'audio/sa.ogg',
    'css/style.css',
    'fonts/diploma_regular-webfont.woff',
    'fonts/diploma_regular-webfont.woff2',
    'img/backgrounds/1.jpg',
    'img/backgrounds/2.jpg',
    'img/backgrounds/3.jpg',
    'img/backgrounds/4.jpg',
    'img/logos/casual-rp.png',
    'img/logos/preload.gif',
    'img/masks/1-1.png',
    'img/masks/1-2.png',
    'img/masks/1-3.png',
    'img/masks/1-4.png',
    'img/masks/2-1.png',
    'img/masks/2-2.png',
    'img/masks/2-3.png',
    'img/masks/2-4.png',
    'img/masks/3-1.png',
    'img/masks/3-2.png',
    'img/masks/3-3.png',
    'img/masks/3-4.png',
    'img/masks/4-1.png',
    'img/masks/4-2.png',
    'img/masks/4-3.png',
    'img/masks/4-4.png',
    'js/jquery.js',
    'js/loader.js',
    'index.html'
}

loadscreen 'index.html'